arucos:
  - id: 6
    position:
      x: 0.0
      y: 3.5
    orientation: -3.14159

  - id: 31
    position:
      x: 3.5
      y: 0 
    orientation: -1.5708

  - id: 32
    position:
      x: 7.0
      y: 3.5
    orientation: 0.0

  - id: 33
    position:
      x: 3.5
      y: 7.0
    orientation: 1.5708
