arucos:
  - id: 9
    position:
      x: 1.5
      y: 0.0
    orientation: -1.5708

  - id: 6
    position:
      x: 3.5
      y: 0.0
    orientation: -1.5708

  - id: 11
    position:
      x: 5.5
      y: 0.0
    orientation: -1.5708

  - id: 3
    position:
      x: 7.0
      y: 1.5
    orientation: 0.0

  - id: 32
    position:
      x: 7.0
      y: 3.5
    orientation: 0.0

  - id: 33
    position:
      x: 7.0
      y: 5.5
    orientation: 0.0

  - id: 4
    position:
      x: 5.5
      y: 7.0
    orientation: 1.5708

  - id: 10
    position:
      x: 3.5
      y: 7.0
    orientation: 1.5708
  
  - id: 1
    position:
      x: 1.5
      y: 7.0
    orientation: 1.5708