waypoints:
  - {id: 1, 'x': 5.0, 'y': 0.0, 'yaw': 0.0}
  - {id: 2, 'x': 0.0, 'y': 5.0, 'yaw': 0.0}
  - {id: 3, 'x': 5.0, 'y': 5.0, 'yaw': 0.0}
  - {id: 4, 'x': 0.0, 'y': 0.0, 'yaw': 0.0}
  - {id: 5, 'x': 2.5, 'y': 2.5, 'yaw': 0.0}
